[FEAT] 로그인 시 토큰 반환 기능을 구현한다.
chin-da/Backend pull request #16
Opened 2023-08-22 14:56 UTC by Jin409

## 📌 관련 이슈
- closed #11 

## ✨ 구현 내용
- 토큰 생성 기능
- 로그인 시 토큰 반환

2023-08-26 04:46 UTC, younghch requested changes
비대칭키 사용해주시고 테스트도 작성해주시면 좋을 것 같아요!

2023-08-26 04:46 UTC, younghch commented on auth/src/main/java/com/auth/auth/service/JwtProvider.java
> +                .setSubject("access_token")
Request: 지금 sub속성에 access_token이 들어가있네요. 헤더에 jwt이라는 것을 명시해줬으니 따로 access_token 속성명을 보내지는 않아도 될것같습니다.

2023-08-26 04:46 UTC, younghch commented on auth/src/main/java/com/auth/auth/service/JwtProvider.java
> +    public boolean verifyToken(String token) {
Request: 테스트 작성해주세요. 제가 테스트 작성해서 실행해봤을때는 토큰 검증에 실패합니다.

2023-08-26 04:46 UTC, younghch commented on auth/src/main/java/com/auth/auth/service/JwtProvider.java
> +            final Claims claims = getBody(token);
Suggest: jjwt라이브러리에서 parseClaimsJws 매소드를 호출할때 signature검증이 이뤄지는 것 같습니다. 지금 라인에서 검증이 이뤄지는건 맞지만 함수의 역할은 body를 가져오는거네요. 두 역할을 명확히 구분해주시거나, verifyToken함수를 삭제하고 getBody만 남겨서 SignqtureException을 처리하는쪽으로 가도 좋을것같아요.

2023-08-26 04:46 UTC, younghch commented on auth/src/main/java/com/auth/auth/service/JwtProvider.java
> +                .setExpiration(new Date(now.getTime() + 120 * 60 * 1000L)); // TODO: 유효기간 상수로 빼기
Question: TODO 지금 처리 안하신 이유가 있나요?

2023-08-26 04:46 UTC, younghch commented on auth/src/main/java/com/auth/auth/service/OAuthService.java
> +        return oAuthClient.getUser(TOKEN_PREFIX + accessToken).getId();
Question: "Bearer"를 붙여서 넘겨야하는 이유가 궁금합니다~

2023-08-26 12:25 UTC, Jin409 commented on auth/src/main/java/com/auth/auth/service/JwtProvider.java
> +        claims.put("socialId", socialId);
네 동의합니다. 삭제하겠습니다.

2023-08-26 12:32 UTC, Jin409 commented on auth/src/main/java/com/auth/auth/service/JwtProvider.java
> +        claims.put("userId", userId);
수정했습니닷

2023-08-26 12:56 UTC, Jin409 commented on auth/src/main/java/com/auth/auth/service/JwtProvider.java
> +                .signWith(getSigningKey())
확인했습니다! 감사합니다 :)

2023-08-26 12:58 UTC, Jin409 commented on auth/src/main/java/com/auth/auth/service/OAuthService.java
> +        return oAuthClient.getUser(TOKEN_PREFIX + accessToken).getId();
kakao 와 통신 시의 규약입니다!

2023-08-26 13:06 UTC, Jin409 commented on auth/src/main/java/com/auth/auth/service/JwtProvider.java
> +            final Claims claims = getBody(token);
수정했습니다!

2023-08-26 13:06 UTC, Jin409 commented on auth/src/main/java/com/auth/auth/service/JwtProvider.java
> +            final Claims claims = getBody(token);
수정했습니다!

2023-08-28 14:43 UTC, younghch requested changes
rsa로 jwt서명해주신것 확인했습니다. 키만 환경변수로 바꿔주시면 좋을 것 같아요. 수고하셨습니다~

2023-08-28 14:43 UTC, younghch commented on auth/src/test/java/com/auth/auth/service/JwtProviderTest.java
> +@SpringBootTest
Suggest: JwtProvider의 기능을 검증하는데는 스프링 부트 서버가 필요하지 않습니다. 예를들어 DB가 떠있지 않은경우 지금 테스트들은 스프링서버가 실행이 안되서 전체 실패하는 것으로 뜹니다. spingBootTest를 지우고 Autowired대신 `private final JwtProvider jwtProvider = new JwtProvider();`로 선언해 주시는것도 좋을 것 같습니다.

2023-08-28 14:43 UTC, younghch commented on auth/src/main/java/com/auth/auth/service/JwtProvider.java
> +        keyPair = keyPairGenerator.generateKeyPair();
Request: 지금처럼 서버에서 동적으로 키를 생성하면 서버가 다운되서 재시작되거나 트래픽이 늘어나 서버를 증가시키면 사용하는 키가 불일치하게 됩니다. Auth-a 서버에서 발급한 토큰을 Auth-b에서는 잘못된 토큰으로 인식하게 될것같습니다.

`ssh-keygen -t rsa -b 2048`명령어를 통해 키를 생성할 수 있습니다. 지난번 설정해 주신것처럼 퍼블릭과 프라이빗 키를 환경변수에서 가져오게 해주시면 좋을 것 같아요.

2023-08-28 14:43 UTC, younghch commented on auth/src/test/java/com/auth/auth/service/JwtProviderTest.java
> +        String token = makeToken();
Suggest: verifyToken테스트가 makeToken에 의존하고 있습니다. token을 유효기간이 매우 긴 구체적인 토큰 값으로 하드코딩해주는게 더 좋을 것 같아요.

ex) `token="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTMyMzMxMjYsImV4cCI6MTY5MzI0MDMyNiwic3ViIjoxfQ.FbNqPzc_TrrBOVU5q5IKFds8rno-KzlA-kbyqUzlXBSgx9izWrGEjDj-Ipv9sPVT9YNQUlp3PKADVsqvSdtxVfYbofI0I311QnGx7yv0sqO2lR4IIbPUtr15E6pj4xyZ2SwihC9UDKc7Tu9BJrfATJyLwq0JYnIWBuNlobbAOfOui3h9BYVSKb4s0JrgH78lJpl2KptBFWt65odnB9G_lgK9dh6jrNTvYxnK0I1nCRNAd5-1XSE-lz-yionIW0WTtTBROwj9KhBKhXO0fPJT8wl0ESxZVvGoY8ix7UELIh9NJyGD79zdk3ScG7k9NXKU8ngRkjA_Mz06UT8ghEw-IQ"`

테스트를 이렇게 짜면 테스트 코드를 여러번 돌렸을 때 지금 코드에서는 키가 바뀌어 실패한다는 것을 발견할 수 있었을 것 같습니다.

2023-08-28 14:43 UTC, younghch commented on api/src/main/java/com/api/api/ApiResponse.java
> +//    public static ApiResponse success(Success success) {
Question: 여기 코드는 작업중이신건가요?

2023-09-05 14:24 UTC, younghch approved these changes
키 관련은 다른 태스크에서 진행하겠습니다. 수고하셨습니다.

2023-09-05 15:48 UTC, merged