Feature/#15 exception
chin-da/Backend pull request #20
Opened 2023-08-28 06:46 UTC by Jin409

## 📌 관련 이슈
- closed #

## ✨ 구현 내용
- e.g. ~ 기능 구현

## (선택) 💬 논의 사항
-

2023-09-04 14:54 UTC, younghch requested changes
Spring 서버에서 에러 잡고 응답 내보내는 부분 너무 잘 짜주신 것 같아요!
에러 정의하신 부분에 몇가지 의문점이 있어 리뷰 드렸습니다.

2023-09-04 14:54 UTC, younghch commented on common/src/main/java/com/common/common/exception/ErrorCode.java
> +    NOT_FOUND_USER_EXCEPTION(HttpStatus.NOT_FOUND, "존재하지 않는 사용자입니다."),
Nit: USER_NOT_FOUND_EXCEPTION 으로 이름을 바꾸면 더 자연스러울 것 같아요!

2023-09-04 14:54 UTC, younghch commented on common/src/main/java/com/common/common/exception/ErrorCode.java
> +    NOT_FOUND_USER_EXCEPTION(HttpStatus.NOT_FOUND, "존재하지 않는 사용자입니다."),
Suggest: 그리고 404는 유저뿐만이 아니라[ RESOURCE_NOT_FOUND](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404)가 더 맞는것 같습니다.

2023-09-04 14:54 UTC, younghch commented on common/src/main/java/com/common/common/exception/model/CustomException.java
> +    private final ErrorCode error;
Suggest: ErrorCode클래스를 통해 상태코드마다 메시지를 고정해주고 싶으셨던 것 같은데, 코드만 ENUM으로 정의하고 메시지는 UserExcpetion, RankingException과 같이 CustomException을 extend한 클래스에서 정해주는게 더 나을 것 같습니다.

예를들어 400에러에 대해서 '잘못된 생년월일', '너무 큰 몸무게' 와 같은 에러 메시지가 가능할것 같은데, ENUM으로 코드에대해서 메시지를 고정하면 어려움이 있을것 같아요.

2023-09-04 14:54 UTC, younghch commented on common/src/main/java/com/common/common/exception/model/NotFoundException.java
> +    public NotFoundException(ErrorCode error) {
Question: NotFoundException에는 404에러 코드를 고정하시는게 원래 의도셨나요? 이렇게 정의하면 실수로 잘못된 ErrorCode객체를 사용해 NotFoundException에 418 I'm a teapot Exception을 넣는것도 가능해질것 같습니다.

2023-09-04 14:54 UTC, younghch commented on common/src/main/java/com/common/common/exception/model/CustomException.java
> +        this.error = error;
Question: super(error.getMessage())를 호출하면 CustomException의 message필드에 ErrorCode의 메시지가 세팅되는거니까 같은 메시지를 두개 가지게 되는게 아닌가 싶습니다.
원래 의도는 ErrorCode eum객체로 default message를 정의하고 필요한경우 다른 메시지를 담는것인가요?

2023-09-05 06:17 UTC, Jin409 commented on common/src/main/java/com/common/common/exception/model/CustomException.java
> +    private final ErrorCode error;
네! 위의 부분에 대해서는 동의합니다.

저는 개인적으로 400 에러에 대해서는 validation 을 이용하면 설정해놓은 메시지가 알아서 바인딩이 되는 걸로 알고 있어서 굳이 extend 한 클래스에서 정의해줄 필요가 없을 것 같아요..!
```
implementation 'org.springframework.boot:spring-boot-starter-validation
```

```java
@NotNull(message = "제목은 빈 칸으로 둘 수 없습니다.")
private String title;
```

위와 같이 하고 400 에러를 핸들링해주면 될 것 같아요.

그러면 ErrorCode 에서 메시지를 정의하는 부분을 빼고 차라리 예외를 던질 때 메시지를 정의하는 건 어떨까요?
저는 예외를 던질 때 메시지를 정의하는게 중복될까봐 ErrorCode 에 정의하려고 했던 거였어요!

2023-09-05 06:21 UTC, Jin409 commented on common/src/main/java/com/common/common/exception/ErrorCode.java
> +    NOT_FOUND_USER_EXCEPTION(HttpStatus.NOT_FOUND, "존재하지 않는 사용자입니다."),
오옹 감사합니다 :)

2023-09-05 06:22 UTC, Jin409 commented on common/src/main/java/com/common/common/exception/model/NotFoundException.java
> +    public NotFoundException(ErrorCode error) {
그럼 ErrorCode 라는 객체를 아예 없애고 exception 모델에 내부적으로 status code 를 정의할까요?

2023-09-05 06:27 UTC, Jin409 commented on common/src/main/java/com/common/common/exception/model/CustomException.java
> +        this.error = error;
아뇨!
저는 CustomException 이 RuntimeException 를 상속했기 때문에 message 를 넘겨야해서 ErrorCode 를 받고 RuntimeException 에도 message 를 넘길 수 있도록 구성했어요. 단순히 이 이유이기는 했는데.. 흠...

2023-09-05 14:52 UTC, younghch commented on common/src/main/java/com/common/common/exception/model/CustomException.java
> +    private final ErrorCode error;
CustomException이름을 오해해서 사용자가 정의한 모든 에러 객체가 상속해야되는 베이스 에러 클래스로 생각했어요. 코드를 다시보니 GlobalHandler에서 특정 status코드에대해 메시지를 고정하려고 하신거군요.

2023-09-05 14:58 UTC, younghch commented on common/src/main/java/com/common/common/exception/model/CustomException.java
> +    private final ErrorCode error;
의도하신 방향이 스테이터스에 대해 메시지 고정이라면 CustomException이 필드로 httpStatus를 가지고 지금 ErrorCode enum 유지한채로 생성자에서 받아서 메시지와 스테이터스 코드에 ErrorCode클래스 값을 세팅하면 될것같습니다.

2023-09-05 15:39 UTC, Jin409 commented on common/src/main/java/com/common/common/exception/model/CustomException.java
> +    private final ErrorCode error;
좋습니다! 이해했습니다 :)

2023-09-09 00:59 UTC, younghch submitted a review, later dismissed
수정해주신 내용 확인했습니다~ 깔끔하고 역할이 잘 보이는 것 같아요! 수고 많으셨습니다.

2023-09-11 13:06 UTC, younghch approved these changes
추가하신 내용 확인했습니다. 수고하셨습니다~

2023-09-12 09:54 UTC, merged